// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingData.Models;

#nullable disable

namespace VendingData.Migrations
{
    [DbContext(typeof(VendingDbContext))]
    [Migration("20220809204326_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VendingData.Models.MasterProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MasterProducts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Mineral Water",
                            Price = 4000m,
                            Quantity = 10
                        },
                        new
                        {
                            ID = 2,
                            Name = "Soft Drink",
                            Price = 8000m,
                            Quantity = 10
                        },
                        new
                        {
                            ID = 3,
                            Name = "Milk",
                            Price = 6000m,
                            Quantity = 10
                        },
                        new
                        {
                            ID = 4,
                            Name = "Coffee",
                            Price = 10000m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("VendingData.Models.MoneyBox", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Denomination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MoneyBox");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Denomination = 100000m,
                            Quantity = 10
                        },
                        new
                        {
                            ID = 2,
                            Denomination = 50000m,
                            Quantity = 10
                        },
                        new
                        {
                            ID = 3,
                            Denomination = 20000m,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 4,
                            Denomination = 10000m,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 5,
                            Denomination = 5000m,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 6,
                            Denomination = 2000m,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 7,
                            Denomination = 1000m,
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("VendingData.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VendingData.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("VendingData.Models.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VendingData.Models.OrderDetail", b =>
                {
                    b.HasOne("VendingData.Models.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VendingData.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
